// Base64-embed a GLB into src/embeddedGlb.ts for the standalone single-file build.
// Usage: node scripts/embed.mjs <path-to.glb>
//
// The standalone viewer must NOT depend on Draco (no decoder fetch on file://),
// so feed it a decoder-free GLB. Produce one from the Draco asset with:
//   npx @gltf-transform/cli simplify ../app/assets/ace-3d/ace.glb /tmp/s.glb --ratio 0.1 --error 0.01
//   npx @gltf-transform/cli optimize /tmp/s.glb /tmp/ace.web.glb \
//       --compress quantize --texture-compress webp --texture-size 1024 --simplify false
//   node scripts/embed.mjs /tmp/ace.web.glb
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const src = process.argv[2];
if (!src) {
  console.error("usage: node scripts/embed.mjs <path-to.glb>");
  process.exit(1);
}
const b64 = readFileSync(src).toString("base64");
const out = path.resolve(here, "../src/embeddedGlb.ts");
writeFileSync(
  out,
  `// AUTO-GENERATED by scripts/embed.mjs — base64 of a decoder-free ACE GLB.\n` +
    `// Do not edit by hand; git-ignored.\nexport const GLB_B64 = "${b64}";\n`,
);
console.log(`embedded ${(b64.length / 1024 / 1024).toFixed(2)} MB → src/embeddedGlb.ts`);
